---
versie: 0.9

subject: Projectbeschrijving xxx
title: xxx 
subtitle: Projectbeschrijving en -verantwoording, v. {{< meta versie >}}
author: "Lectoraat Learning Technology & Analytics"
keywords: [De HHs]
lang: nl
date: last-modified
date-format: "DD-MM-YYYY"

format: 
  pdf: 
    output-file: LTA-HHs-[Naam-met-streepjes]_0.9
    output-ext:  "pdf"
template: 00_Templates/eisvogel-lta.latex
number-sections: true
number-depth: 3
listings: true
latex-output-dir: 05_Output

titlepage: true,
titlepage-rule-color: 'FFFFFF'
titlepage-text-color: '223343'
titlepage-title-color: '223343'
titlepage-subtitle-color: '9EA700'
titlepage-footer-color: 'FFFFFF'
titlepage-background: 01_Backgrounds/LTA-fairness-pionnen.pdf

header-title-color: '9EA700'
header-date-color: '777777'
footer-author-color: '777777'
footer-pagenumber-color: '777777'

toc: true
toc-depth: 3
toc-own-page: true
colorlinks: true
table-use-row-colors: false
footnotes-pretty: true
link-citations: true
bibliography: 03_Bibliography/biblio.bib
csl: 04_Styles/apa.csl
editor: visual

filters:
  - _extensions/color-text/color-text.lua
---

# Inleiding

## Samenvatting

**Het onderzoeksproject \[Naam\] van het lectoraat Learning Technology & Analytics (LTA) heeft tot doel ....**

\[samenvatting\]

Het onderzoeksproject wordt uitgevoerd door \[naam + functie + contactgegevens onderzoeker(s)\] en begeleid door de lector, Dr. Theo C. Bakker ([t.c.bakker\@hhs.nl](mailto:t.c.bakker@hhs.nl)).

## Wat hebben opleidingen en studenten aan dit onderzoeksproject?

**Studenten** ...

**Opleidingen** ....

## Wat heeft De HHs aan dit onderzoeksproject?

Dit onderzoeksproject draagt bij aan het instellingsplan van De HHs '[Onderzoekend leren met impact](https://www.dehaagsehogeschool.nl/sites/hhs/files/documents/OverDeHaagse-Organisatie-FeitenDocumenten-instellingsplan-02-15-def.pdf)'. In het bijzonder aan de strategische thema's ...

## Positie van het project in de onderzoekslijnen van het lectoraat, het kenniscentrum en De HHs

Het project draagt bij aan de onderzoekslijnen ... van het lectoraat. ...

Het onderzoek valt verder in de onderzoekslijn Transformative Technology van het Kenniscentrum Global & Inclusive Learning en sluit aan bij de onderzoeksthema's Digitale Toekomst / Rechtvaardige Samenleving / Duurzaamheid van De HHs \[maak hier een keuze uit\].

## Doel en opbouw van dit document

Dit document beschrijft de verdere onderbouwing van het belang van het project (hoofdstuk 2), de operationalisering en onderzoeksvragen van het project (hoofdstuk 3), de bronnen die we daarvoor gebruiken (hoofdstuk 4), het proces van dataverzameling (hoofdstuk 5), de methoden van analyse (hoofdstuk 6), de planning (hoofdstuk 7), de verwachte resultaten en eventuele beperkingen (hoofdstuk 8), de reproduceerbaarheid van het onderzoek (hoofdstuk 9) en tot slot het budget en financiering (hoofdstuk 10).

\newpage

# Onderbouwing van het belang

Dit hoofdstuk bevat een theoretische en ethische onderbouwing van het belang van het onderzoeksproject.

## Theoretische onderbouwing

...

## Ethische overwegingen

Vanuit het principe van academische integriteit is dit document opgesteld om transparant te zijn in het onderzoek en verantwoording af te leggen over de verzamelde data en toegepaste methoden. In deze paragraaf lichten we op hoofdlijnen toe welke ethische overwegingen zijn gemaakt. In bijlage 1 wordt een aantal ethische vragen behandeld.

...

\newpage

# Methode

## Onderzoeksvragen en operationalisering

\[Beschrijf de onderzoeksvragen en de operationalisering daarvan.\]

...

## Afbakening

Dit onderzoek beperkt zich tot...

\newpage

# Methoden van analyse

In dit hoofdstuk beschrijven we per onderzoeksvraag van het onderzoek de methode van analyse.

...

\newpage

# Planning

In dit hoofdstuk beschrijven we per onderdeel van het onderzoek de planning van activiteiten en resulterende producten.

\[Deel de planning in met een tabel met de volgende kolommen Datum, Activiteit, Door/met wie, Product\]

...

\newpage

# Verwachte resultaten en beperkingen {data-link="Verwachte resultaten"}

## Resultaten

De resultaten van het onderzoek zullen op de volgende manieren beschikbaar worden gesteld:

\[Beschrijf de resultaten die je verwacht, hoe je die ter beschikking gaat stellen en aan wie\]

...

## Beperkingen

Het onderzoek kent mogelijk de volgende beperkingen:

\[Geef een opsomming van beperkingen en hoe daarmee wordt omgegaan\]

...

\newpage

# Reproduceerbaarheid {data-link="Reproduceerbaarheid"}

Het onderzoek volgt de [FAIR principes](https://www.go-fair.org/fair-principles/) voor reproduceerbaarheid van onderzoeksresultaten: **F**indability (vindbaarheid), **A**ccessability (toegankelijkheid), **I**nteroperability (uitwisselbaarheid), en **R**euse (herbruikbaarheid) van digitale assets. We betrekken dit op dataverzameling en beroepsproducten. ...

\newpage

# Budget en financiering

\[Beschrijf per activiteit de verwachte inzet en hoe deze wordt bekostigd.\]

\newpage

# Referenties {.unnumbered}

::: {#refs}
:::

\newpage

# Versiegeschiedenis {.unnumbered}

-   \[voor elke versie een regel met de datum, de aanpassing en - indien van toepassing - de verspreiding\]

# Repository {.unnumbered}

De broncode voor dit document kan bewerkt worden via [GitHub](https://github.com/LTA-HHs/%5Bgit-url%5D). Leden van de kenniskring van het lectoraat kunnen op verzoek toegang krijgen en meewerken aan de inhoud.

\newpage

# Bijlage 1 - Ethics Checklist voor kwalitatief onderzoek {.unnumbered}

## A. Denk na

Neem afstand van het project, denk na over het werk dat je gaat doen en de ethische kwesties die zich in alle fasen van het onderzoek kunnen voordoen. Denk na over de specifieke ethische overwegingen rond de door jou gekozen methodologie en de impact die deze hebben op de gegevensverzameling, analyse en je algehele resultaten.

Probeer na te denken over eventuele risico's en neem maatregelen om ze te voorkomen. Zowel door gebruik te maken van het advies in onze richtlijnen als door indien nodig verdere ondersteuning te zoeken.

## B. Voorkom schade

Deelnemers mogen geen schade ondervinden van deelname aan je onderzoek. Je moet alle mogelijke risico's voor zowel deelnemers als onderzoekers in kaart brengen.

Heb je de nodige ondersteuning voor zowel deelnemers als onderzoekers voorhanden, mochten ze die nodig hebben?

| Aandachtspunt         | Overwegingen                                                                                                   |
|-----------------------|----------------------------------------------------------------------------------------------------------------|
| **B.1 Ondersteuning** | Heb je de nodige ondersteuning voor zowel deelnemers als onderzoekers voorhanden, mochten ze die nodig hebben? |
|                       | ...                                                                                                            |

: {tbl-colwidths="\[25,75\]"}

## C. Methode en kwaliteit

| Aandachtspunt                           | Overwegingen                                                                                                                                            |
|-----------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
| **C.1 Beperkingen**                     | Heb je nagedacht over de beperkingen van de gekozen methode en de invloed die dit kan hebben op de gegevensverzameling, analyse en algemene resultaten? |
|                                         | ...                                                                                                                                                     |
| **C.2 Specifieke ethische kwesties**    | Heb je de specifieke ethische kwesties met betrekking tot je methode overwogen?                                                                         |
|                                         | ...                                                                                                                                                     |
| **C.3 Geschiktheid van de methode**     | Is de methode geschikt voor de deelnemersgroep?                                                                                                         |
|                                         | ...                                                                                                                                                     |
| **C.4 Ervarenheid van de onderzoekers** | Zijn de onderzoekers bedreven in de gekozen methode?                                                                                                    |
|                                         | ...                                                                                                                                                     |
| **C.5 Onderzoeksvragen en methode**     | Heb je een duidelijk gedefinieerde onderzoeksvraag? Is je methode het meest geschikt om deze te beantwoorden?                                           |
|                                         | ...                                                                                                                                                     |
| **C.6 Toegankelijkheid**                | Is je methode van gegevensverzameling toegankelijk voor je deelnemersgroep en weerspiegelt deze de individuele behoeften om deel te nemen?              |
|                                         | ...                                                                                                                                                     |
| **C.7 Vooringenomenheid**               | Heb je rekening gehouden met je eigen vooringenomenheid en hoe je eigen meningen en ervaringen elke fase van het onderzoeksproject kunnen beïnvloeden?  |
|                                         |                                                                                                                                                         |

: {tbl-colwidths="\[25,75\]"}

Vermijd het gebruik van suggestieve vragen bij het verzamelen van gegevens. Leidende vragen kunnen de antwoorden van deelnemers beïnvloeden en uw algemene onderzoeksresultaten beïnvloeden. Het gebruik van een onderwerpsleidraad om discussies te vergemakkelijken kan helpen om het aantal of de waarschijnlijkheid van suggestieve vragen te verminderen.

## D. Publiek goed

| Aandachtspunt                             | Overwegingen                                                                                                                                                             |
|-------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **D.1 Voordelen versus risico's**         | Denk na over wat je van plan bent te doen met de bevindingen, wegen de voordelen op tegen de risico's?                                                                   |
|                                           | ...                                                                                                                                                                      |
| **D.2 Communicatie van voordelen**        | Heb je de voordelen van je onderzoek duidelijk gedocumenteerd?                                                                                                           |
|                                           | ...                                                                                                                                                                      |
| **D.3 Representatie van de deelnemers**   | Kun je ervoor zorgen dat je bevindingen de ervaringen en meningen van de deelnemersgroep weerspiegelen?                                                                  |
|                                           | ...                                                                                                                                                                      |
| **D.4 Bijdrage aan bestaande wetenschap** | Heb je de nodige literatuuronderzoeken gedaan om er zeker van te zijn dat je onderzoek huidige hiaten heeft geïdentificeerd of bijdraagt aan reeds bestaande informatie? |
|                                           | ...                                                                                                                                                                      |

: {tbl-colwidths="\[25,75\]"}

## E. Transparentie

| Aandachtspunt                                         | Overwegingen                                                                                                 |
|-------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| **E.1 Communicatie over het onderzoeksproces**        | Heb je duidelijk gecommuniceerd hoe je de gegevens gaat verzamelen, opslaan, analyseren, gebruiken en delen? |
|                                                       | ...                                                                                                          |
| **E.2 Communicatie over deelname**                    | Kan je duidelijk aangeven hoe deelname aan het onderzoek eruitziet?                                          |
|                                                       | ...                                                                                                          |
| **E.3 Communicatie over aanbevelingen en resultaten** | Heb je overwogen hoe je publiek het beste met je aanbevelingen en resultaten kan omgaan?                     |
|                                                       | ...                                                                                                          |

: {tbl-colwidths="\[25,75\]"}

## F. Vertrouwelijkheid en gegevensbeveiliging

+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Aandachtspunt                            | Overwegingen                                                                                                                                                                                                                                                                                                                                                                                                                             |
+==========================================+==========================================================================================================================================================================================================================================================================================================================================================================================================================================+
| **A.1 Vertrouwelijkheid en anonimiteit** | Heb je overwogen hoe je de vertrouwelijkheid en anonimiteit van deelnemersgegevens te allen tijde zult handhaven?                                                                                                                                                                                                                                                                                                                        |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          | ...                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **A.2 Waarborging anonimiteit**          | Ben je in staat om de anonimiteit van personen in uw bevindingen te waarborgen, zelfs als persoonlijke identificatiemiddelen zijn verwijderd?                                                                                                                                                                                                                                                                                            |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          | ...                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **A.3 Locatie**                          | De locatie waar de gegevensverzameling plaatsvindt, kan van invloed zijn op hoe prettig zowel de onderzoeker als de deelnemer zich voelt. Dit kan weer van invloed zijn op de kwaliteit van de verzamelde informatie. Je moet ook overwegen hoe privé de locatie is. Is er iemand anders aanwezig? Is er een kans dat het gesprek wordt afgeluisterd?  \                                                                                 |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          | ...                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **A.4 Persoonlijke levenssfeer**         | Er kunnen zich situaties voordoen waarin je de vertrouwelijkheid moet verbreken als een deelnemer informatie onthult waardoor je je zorgen maakt over zijn of haar veiligheid of die van iemand anders. Beschik je over de noodzakelijke procedure om de vertrouwelijkheid te verbreken als dat nodig is? Ben je op de hoogte van de relevante instanties voor bescherming van persoonlijke levenssfeer waarmee je contact kunt opnemen? |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          | ...                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[25,75\]"}

## G. Wettelijke naleving

| Aandachtspunt                     | Overwegingen                                                                                                    |
|-----------------------------------|-----------------------------------------------------------------------------------------------------------------|
| **A.1 Wettelijke verplichtingen** | Heb je nagedacht over je wettelijke verplichtingen bij het verzamelen en opslaan van persoonlijke informatie?   |
|                                   | ...                                                                                                             |
| **A.2 Beschermingsprocedure**     | Beschik je over de juiste beschermingsprocedures voor het geval een deelnemer u iets vertelt dat u moet melden? |
|                                   | ...                                                                                                             |
| **A.3 Beperking va informatie**   | Weet u hoeveel informatie u moet verzamelen om uw vraag te kunnen beantwoorden?                                 |
|                                   | ...                                                                                                             |

: {tbl-colwidths="\[25,75\]"}

*Bron*: [Ethical considerations associated with Qualitative Research methods van de UK Statistics Authority](https://uksa.statisticsauthority.gov.uk/publication/ethical-considerations-associated-with-qualitative-research-methods/pages/8/)**.** Vertaald door T. Bakker met behulp van Deepl.
